# Generated by Django 3.2.16 on 2023-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.FileField(null=True, upload_to='photo'),
        ),
    ]
